apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oxpxsztty-dotnet-basic
  janus-idp.io/tekton: oxpxsztty-dotnet-basic
  backstage.io/kubernetes-id: oxpxsztty-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oxpxsztty-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
